// <auto-generated />
namespace Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSessionToArtist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSessionToArtist));
        
        string IMigrationMetadata.Id
        {
            get { return "201209261714117_AddSessionToArtist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
