// <auto-generated />
namespace Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddSignalRConnections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSignalRConnections));
        
        string IMigrationMetadata.Id
        {
            get { return "201210021727493_AddSignalRConnections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
